export type PaymentMethod =
  | 'airtel_money'
  | 'tnm_mpamba'
  | 'bank_transfer'
  | 'card';

export type PaymentStatus =
  | 'pending'      // Record created, not sent to provider
  | 'processing'   // Sent to provider, awaiting callback
  | 'paid'         // Webhook confirmed success
  | 'failed'       // Webhook confirmed failure
  | 'refunded'     // Refund processed
  | 'expired';     // Timed out (30 min) without resolution

export interface Payment {
  id: string;
  shipment_id: string;
  user_id: string;
  amount_mwk: number;                    // Tambala (MWK × 100)
  method: PaymentMethod;
  status: PaymentStatus;
  provider_reference: string | null;     // Paychangu tx_ref
  provider_transaction_id: string | null;
  idempotency_key: string;               // UUID generated by client
  phone_number: string | null;           // For mobile money methods
  callback_received_at: string | null;
  callback_payload: Record<string, unknown> | null;  // Raw webhook body
  failure_reason: string | null;
  expires_at: string | null;             // 30 min from creation
  created_at: string;
  updated_at: string;
}

export interface PaymentInitiateRequest {
  shipment_id: string;
  method: PaymentMethod;
  phone_number?: string;                 // Required for mobile money
}

export interface PaymentInitiateResponse {
  payment_id: string;
  provider_reference: string;
  status: PaymentStatus;
  expires_at: string;
}
