import { z } from 'zod';

const UUID_V4_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export const InitiatePaymentSchema = z.object({
  shipment_id: z
    .string()
    .uuid('Invalid shipment ID'),
  method: z.enum(
    ['airtel_money', 'tnm_mpamba', 'bank_transfer', 'card'],
    { errorMap: () => ({ message: 'Please select a valid payment method' }) },
  ),
  phone_number: z
    .string()
    .regex(/^\+?[0-9]{9,15}$/, 'Enter a valid phone number')
    .optional(),
  /**
   * UUID v4 generated by the mobile client before the first payment attempt.
   * Reused on retries. Prevents duplicate charges on network failure.
   */
  idempotency_key: z
    .string()
    .regex(UUID_V4_REGEX, 'idempotency_key must be a valid UUID v4'),
});

export const DisputeCreateSchema = z.object({
  shipment_id: z.string().uuid(),
  category: z.enum([
    'package_damaged',
    'package_lost',
    'not_delivered',
    'wrong_delivery',
    'payment_issue',
    'other',
  ]),
  description: z
    .string()
    .min(20, 'Please provide at least 20 characters describing the issue')
    .max(2000)
    .trim(),
  evidence_urls: z.array(z.string().url()).max(5).optional().default([]),
});

export type InitiatePaymentInput = z.infer<typeof InitiatePaymentSchema>;
export type DisputeCreateInput   = z.infer<typeof DisputeCreateSchema>;
