/**
 * payment.service.ts — Payment lifecycle business logic.
 *
 * Orchestrates:
 *   - Payment initiation (idempotency key enforcement, Paychangu call, DB write)
 *   - Webhook processing (HMAC verified upstream, DB atomic advancement)
 *   - Payment status retrieval (ownership-enforced)
 *   - Shipment payment history (ownership-enforced)
 *
 * SECURITY CONTRACT:
 *   - actorId is always taken from req.user.id, NEVER from request body
 *   - Idempotency key is validated as a UUID before use
 *   - Provider reference (tx_ref) is generated server-side, never from client
 *   - Amount is taken from the shipment record, never from the payment request body
 *   - Webhook signature verification happens in the route handler, not here
 *   - This service trusts that webhook payloads are HMAC-verified before arrival
 *
 * Monetary invariants:
 *   - All amounts stored and computed in tambala (MWK × 100)
 *   - Paychangu receives amount in MWK (whole number = tambala / 100)
 *   - The amount sent to Paychangu must match shipment.final_price_mwk
 *     (or quoted_price_mwk if final_price_mwk is null)
 *   - We verify Paychangu's callback amount matches our stored amount
 *
 * Database access patterns:
 *   - initiatePayment:  1 shipment SELECT + 1 payment INSERT + 1 Paychangu call
 *                       + 1 payment UPDATE (provider_reference) + 1 audit write
 *   - processWebhook:   1 DB RPC call (atomic)
 *   - getPayment:       1 SELECT + ownership check
 *   - getShipmentPayments: 1 SELECT
 */

import crypto from 'crypto';

import { tambalaToMwk } from '@courier/shared-constants';
import type { Payment, PaymentMethod, PaymentStatus } from '@courier/shared-types';

import {
  paychanguClient,
  type PaychanguWebhookPayload,
} from '../clients/paychangu.client.js';
import { env } from '../config/env.js';
import { supabaseServiceRole } from '../config/supabase.js';
import {
  NotFoundError,
  ConflictError,
  BusinessRuleError,
  ValidationError,
  mapSupabaseError,
} from '../errors/app-error.js';
import { logger } from '../utils/logger.js';

import { auditService } from './audit.service.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface InitiatePaymentInput {
  shipment_id:      string;
  method:           PaymentMethod;
  phone_number?:    string;      // Required for airtel_money, tnm_mpamba
  idempotency_key:  string;      // UUID v4 generated by mobile client
}

export interface InitiatePaymentResult {
  payment_id:          string;
  provider_reference:  string;
  status:              PaymentStatus;
  expires_at:          string;
  /** Present for card/web payments; absent for USSD mobile money */
  payment_url?:        string;
}

export interface WebhookProcessResult {
  action:     'advanced' | 'reverted' | 'idempotent_skip' | 'unknown_reference';
  payment_id: string | null;
  status:     PaymentStatus;
}

// ─── Idempotency key validator ────────────────────────────────────────────────

const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function validateIdempotencyKey(key: string): void {
  if (!UUID_REGEX.test(key)) {
    throw new ValidationError('idempotency_key must be a valid UUID v4', [
      {
        field:   'idempotency_key',
        message: 'Must be a UUID v4 (xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx)',
      },
    ]);
  }
}

// ─── Provider reference generator ────────────────────────────────────────────
// We generate the tx_ref server-side. Never use the idempotency_key as the
// tx_ref — the idempotency_key is a client secret for our idempotency layer;
// the tx_ref is what we send to Paychangu and appears in their dashboard.

function generateProviderReference(shipmentId: string): string {
  // Format: PAY-{shipment_id_prefix}-{8 random hex chars}
  const prefix = shipmentId.replace(/-/g, '').substring(0, 8).toUpperCase();
  const random = crypto.randomBytes(4).toString('hex').toUpperCase();
  return `PAY-${prefix}-${random}`;
}

// ─── Payment Service ──────────────────────────────────────────────────────────

class PaymentService {

  // ─── Initiate payment ────────────────────────────────────────────────────

  /**
   * Initiate a payment for an approved shipment.
   *
   * Flow:
   *   1. Validate idempotency key format
   *   2. Check for existing payment with same idempotency_key → return it (idempotent)
   *   3. Load shipment — verify it is in 'approved' state and owned by the caller
   *   4. Generate server-side provider_reference (tx_ref)
   *   5. Create payment record in DB (status: 'pending')
   *      — storing the idempotency_key for future deduplication
   *   6. Set shipment status to 'payment_pending'
   *   7. Call Paychangu to initiate the payment
   *   8. Update payment record with Paychangu's response (status: 'processing')
   *   9. Write audit log
   *
   * Step 5 happens BEFORE step 7 (Paychangu call). If Paychangu call fails,
   * the payment record remains at 'pending'. A retry with the same idempotency_key
   * will detect the existing pending record and attempt the Paychangu call again.
   *
   * Step 6 (shipment advancement to payment_pending) happens atomically with step 5
   * via the DB transaction. If the shipment is already in payment_pending (concurrent
   * initiation), we return a ConflictError.
   */
  async initiatePayment(
    input:   InitiatePaymentInput,
    actorId: string,
    actorIp: string,
  ): Promise<InitiatePaymentResult> {
    const { shipment_id, method, phone_number, idempotency_key } = input;

    // ── Step 1: Validate idempotency key ─────────────────────────────
    validateIdempotencyKey(idempotency_key);

    // ── Step 2: Check idempotency — return existing if found ──────────
    {
      const { data: existing } = await supabaseServiceRole()
        .from('payments')
        .select('*')
        .eq('idempotency_key', idempotency_key)
        .single();

      if (existing) {
        logger.info(
          { paymentId: existing.id, idempotencyKey: idempotency_key },
          'Idempotent payment initiation — returning existing record',
        );

        // If the existing payment is in 'pending' state, the previous Paychangu
        // call may have failed. Retry the Paychangu call now.
        if (existing.status === 'pending') {
          return this.retryPaychanguCall(existing as unknown as Payment, actorIp);
        }

        return {
          payment_id:         existing.id as string,
          provider_reference: existing.provider_reference as string,
          status:             existing.status as PaymentStatus,
          expires_at:         existing.expires_at as string,
        };
      }
    }

    // ── Step 3: Load and validate shipment ────────────────────────────
    const { data: shipment, error: shipmentError } = await supabaseServiceRole()
      .from('shipments')
      .select('id, user_id, status, quoted_price_mwk, final_price_mwk')
      .eq('id', shipment_id)
      .single();

    if (shipmentError || !shipment) {
      throw new NotFoundError('Shipment');
    }

    // Ownership check
    if (shipment.user_id !== actorId) {
      // Return 404 — don't confirm the shipment exists to the wrong user
      throw new NotFoundError('Shipment');
    }

    // State check — must be 'approved' to initiate payment
    if (shipment.status !== 'approved') {
      throw new BusinessRuleError(
        `Payment cannot be initiated: shipment is in '${shipment.status as string}' state. ` +
        `Shipment must be in 'approved' state to accept payment.`,
        'INVALID_STATE_FOR_PAYMENT',
      );
    }

    // Mobile money requires a phone number
    if ((method === 'airtel_money' || method === 'tnm_mpamba') && !phone_number) {
      throw new ValidationError('Phone number is required for mobile money payments', [
        {
          field:   'phone_number',
          message: 'Required for Airtel Money and TNM Mpamba payments',
        },
      ]);
    }

    // ── Step 4: Generate provider reference ───────────────────────────
    const providerReference = generateProviderReference(shipment_id);
    const expiresAt = new Date(Date.now() + 30 * 60 * 1000).toISOString(); // 30 minutes

    // ── Step 5: Create payment record (status: 'pending') ─────────────
    // The payment amount is always taken from the shipment, never from the request.
    // final_price_mwk takes precedence if set by admin.
    const amountTambala = (shipment.final_price_mwk as number | null)
      ?? (shipment.quoted_price_mwk as number);

    const { data: payment, error: insertError } = await supabaseServiceRole()
      .from('payments')
      .insert({
        shipment_id,
        user_id:            actorId,
        amount_mwk:         amountTambala,
        method,
        status:             'pending',
        provider_reference: providerReference,
        idempotency_key,
        phone_number:       phone_number ?? null,
        expires_at:         expiresAt,
      })
      .select('*')
      .single();

    if (insertError) {
      // Unique constraint on idempotency_key: race condition, another request
      // inserted between our check and insert. Return the existing record.
      if (insertError.code === '23505') {
        throw new ConflictError(
          'A payment for this request is already being processed. Please wait.',
        );
      }
      // Unique constraint on (shipment_id) WHERE status IN ('pending','processing'):
      // another active payment exists for this shipment.
      throw mapSupabaseError(insertError);
    }

    if (!payment) {
      throw new Error('Payment insert returned no data');
    }

    // ── Step 6: Advance shipment to 'payment_pending' ─────────────────
    // Optimistic concurrency: only update if still 'approved'
    const { error: shipmentUpdateError } = await supabaseServiceRole()
      .from('shipments')
      .update({ status: 'payment_pending' })
      .eq('id', shipment_id)
      .eq('status', 'approved'); // Concurrency guard

    if (shipmentUpdateError) {
      // Clean up the orphaned payment record
      await supabaseServiceRole()
        .from('payments')
        .delete()
        .eq('id', payment.id as string);

      throw mapSupabaseError(shipmentUpdateError);
    }

    // ── Step 7 + 8: Call Paychangu and update payment ─────────────────
    return this.retryPaychanguCall(payment as unknown as Payment, actorIp);
  }

  /**
   * Attempt (or retry) the Paychangu initiation call for a pending payment.
   * Updates payment status to 'processing' on success.
   */
  private async retryPaychanguCall(
    payment: Payment,
    actorIp: string,
  ): Promise<InitiatePaymentResult> {
    // Load customer info for Paychangu's customer object
    const { data: profile } = await supabaseServiceRole()
      .from('user_profiles')
      .select('full_name, email, phone_number')
      .eq('id', payment.user_id)
      .single();

    const paychanguRequest: any = {
      tx_ref:      payment.provider_reference!,
      amount:      Math.round(tambalaToMwk(payment.amount_mwk)),  // Paychangu receives MWK whole number
      currency:    'MWK' as const,
      payment_type: paychanguClient.mapPaymentMethod(payment.method),
      mobile_number: payment.phone_number ?? undefined,
      description: `Courier delivery payment — Shipment ${payment.shipment_id}`,
      callback_url: `${env.BACKEND_BASE_URL}/api/v1/webhooks/paychangu`,
      customer: {
        name:  (profile?.full_name as string | null) ?? 'Courier Customer',
        email: (profile?.email as string | null) ?? '',
        phone: payment.phone_number ?? (profile?.phone_number as string | null) ?? '',
      },
      meta: {
        payment_id:  payment.id,
        shipment_id: payment.shipment_id,
      },
    };

    let paymentUrl: string | undefined;

    try {
      const paychanguResponse = await paychanguClient.initiatePayment(paychanguRequest);
      paymentUrl = paychanguResponse.data?.payment_url
        ?? paychanguResponse.data?.authorization_url;

      // Update payment to 'processing' — Paychangu accepted it
      await supabaseServiceRole()
        .from('payments')
        .update({ status: 'processing' })
        .eq('id', payment.id);

    } catch (err) {
      // Paychangu call failed — payment remains 'pending' for retry
      logger.error(
        { paymentId: payment.id, err },
        'Paychangu initiation call failed — payment remains pending',
      );
      throw err;
    }

    // Audit log
    await auditService.logPaymentInitiated(
      payment.user_id,
      payment.id,
      payment.shipment_id,
      payment.method,
      actorIp,
    );

    logger.info(
      {
        paymentId:         payment.id,
        shipmentId:        payment.shipment_id,
        providerReference: payment.provider_reference,
        method:            payment.method,
        amountTambala:     payment.amount_mwk,
      },
      'Payment initiated successfully',
    );

    return {
      payment_id:          payment.id,
      provider_reference:  payment.provider_reference!,
      status:              'processing',
      expires_at:          payment.expires_at!,
      payment_url:         paymentUrl,
    } as InitiatePaymentResult;
  }

  // ─── Process webhook ──────────────────────────────────────────────────────

  /**
   * Process a Paychangu webhook callback.
   *
   * PRECONDITION: HMAC signature has been verified by the route handler
   * BEFORE this method is called. This method trusts the payload is authentic.
   *
   * Flow:
   *   1. Determine payment outcome (successful vs failed vs cancelled)
   *   2. Call the appropriate DB RPC (atomic: payment update + shipment update)
   *   3. Return structured result for the route handler to log
   *
   * Unknown tx_ref: if the webhook references a tx_ref we don't recognize,
   * log it and return 'unknown_reference'. Do NOT throw — the webhook handler
   * returns 200 to prevent Paychangu from retrying.
   *
   * Amount mismatch: if Paychangu reports a different amount than we stored,
   * log a CRITICAL alert and mark the payment as failed. This should NEVER happen
   * in normal operation — it indicates either a bug in our pricing or fraud.
   */
  async processWebhook(
    payload: PaychanguWebhookPayload,
    actorIp: string,
  ): Promise<WebhookProcessResult> {
    const { tx_ref, transaction_id, status, amount } = payload;

    logger.info(
      { txRef: tx_ref, status, amount },
      'Processing Paychangu webhook',
    );

    // Look up the payment by our provider_reference
    const { data: existingPayment } = await supabaseServiceRole()
      .from('payments')
      .select('id, status, amount_mwk, shipment_id')
      .eq('provider_reference', tx_ref)
      .single();

    if (!existingPayment) {
      logger.warn(
        { txRef: tx_ref },
        'Webhook received for unknown tx_ref — ignoring',
      );
      return { action: 'unknown_reference', payment_id: null, status: 'failed' };
    }

    const paymentId = existingPayment.id as string;

    // Amount integrity check
    const expectedMwk = Math.round(tambalaToMwk(existingPayment.amount_mwk as number));
    const reportedMwk = Math.round(amount);

    if (status === 'successful' && reportedMwk !== expectedMwk) {
      logger.error(
        {
          txRef:      tx_ref,
          paymentId,
          expectedMwk,
          reportedMwk,
          difference: reportedMwk - expectedMwk,
        },
        'CRITICAL: Paychangu reported amount differs from stored amount — treating as failed',
      );

      // Treat amount mismatch as failure — do not advance shipment
      const { data: revertedPayment } = await supabaseServiceRole().rpc(
        'revert_shipment_on_payment_failure',
        {
          p_provider_reference: tx_ref,
          p_failure_reason:     `Amount mismatch: expected ${expectedMwk} MWK, received ${reportedMwk} MWK`,
          p_callback_payload:   payload as unknown as Record<string, unknown>,
          p_actor_ip:           actorIp,
        },
      );

      return {
        action:     'reverted',
        payment_id: paymentId,
        status:     (revertedPayment as unknown as Payment)?.status ?? 'failed',
      };
    }

    if (status === 'successful') {
      // ── Payment confirmed ───────────────────────────────────────────
      const { data: advancedPayment, error: advanceError } =
        await supabaseServiceRole().rpc('advance_shipment_on_payment', {
          p_provider_reference:      tx_ref,
          p_provider_transaction_id: transaction_id,
          p_callback_payload:        payload as unknown as Record<string, unknown>,
          p_actor_ip:                actorIp,
        });

      if (advanceError) {
        const msg = advanceError.message ?? '';

        // Idempotent: already processed
        if (msg.includes('NOT_FOUND')) {
          logger.warn({ txRef: tx_ref }, 'advance_shipment_on_payment: payment not found');
          return { action: 'idempotent_skip', payment_id: paymentId, status: 'paid' };
        }

        logger.error(
          { txRef: tx_ref, error: advanceError.message },
          'advance_shipment_on_payment RPC failed',
        );
        throw mapSupabaseError(advanceError);
      }

      const result = advancedPayment as unknown as Payment;

      // Idempotent: was already paid
      if (result.status === 'paid' && result.id !== paymentId) {
        return { action: 'idempotent_skip', payment_id: paymentId, status: 'paid' };
      }

      logger.info(
        { txRef: tx_ref, paymentId, shipmentId: existingPayment.shipment_id },
        'Payment confirmed — shipment advanced to payment_confirmed',
      );

      return { action: 'advanced', payment_id: paymentId, status: 'paid' };

    } else {
      // ── Payment failed or cancelled ─────────────────────────────────
      const failureReason =
        status === 'cancelled'
          ? 'Customer cancelled the payment'
          : 'Payment was declined by the provider';

      const { data: revertedPayment, error: revertError } =
        await supabaseServiceRole().rpc('revert_shipment_on_payment_failure', {
          p_provider_reference: tx_ref,
          p_failure_reason:     failureReason,
          p_callback_payload:   payload as unknown as Record<string, unknown>,
          p_actor_ip:           actorIp,
        });

      if (revertError) {
        logger.error(
          { txRef: tx_ref, error: revertError.message },
          'revert_shipment_on_payment_failure RPC failed',
        );
        throw mapSupabaseError(revertError);
      }

      logger.info(
        { txRef: tx_ref, paymentId, status },
        'Payment failed — shipment reverted to approved',
      );

      return {
        action:     'reverted',
        payment_id: paymentId,
        status:     (revertedPayment as unknown as Payment)?.status ?? 'failed',
      };
    }
  }

  // ─── Get payment by ID ────────────────────────────────────────────────────

  /**
   * Fetch a payment record by ID.
   * Customers can only see their own payments.
   * Admins can see any payment.
   */
  async getPayment(
    paymentId: string,
    actorId:   string,
    isAdmin:   boolean,
  ): Promise<Payment> {
    const { data, error } = await supabaseServiceRole()
      .from('payments')
      .select('*')
      .eq('id', paymentId)
      .single();

    if (error || !data) {
      throw new NotFoundError('Payment');
    }

    const payment = data as unknown as Payment;

    if (!isAdmin && payment.user_id !== actorId) {
      throw new NotFoundError('Payment'); // 404, not 403 — don't confirm existence
    }

    return payment;
  }

  // ─── Get payments for a shipment ──────────────────────────────────────────

  /**
   * Fetch all payment records for a shipment (may be multiple — retries).
   * Customers can only see payments for their own shipments.
   * Admins can see any shipment's payments.
   */
  async getShipmentPayments(
    shipmentId: string,
    actorId:    string,
    isAdmin:    boolean,
  ): Promise<Payment[]> {
    // First verify ownership via the shipment record
    const { data: shipment, error: shipmentError } = await supabaseServiceRole()
      .from('shipments')
      .select('id, user_id')
      .eq('id', shipmentId)
      .single();

    if (shipmentError || !shipment) {
      throw new NotFoundError('Shipment');
    }

    if (!isAdmin && (shipment.user_id as string) !== actorId) {
      throw new NotFoundError('Shipment'); // Don't reveal shipment existence
    }

    const { data: payments, error: paymentsError } = await supabaseServiceRole()
      .from('payments')
      .select('*')
      .eq('shipment_id', shipmentId)
      .order('created_at', { ascending: false });

    if (paymentsError) {
      throw mapSupabaseError(paymentsError);
    }

    return (payments ?? []) as unknown as Payment[];
  }
}

// ─── Singleton ────────────────────────────────────────────────────────────────
export const paymentService = new PaymentService();
