-- ═══════════════════════════════════════════════════════════════════
-- 008 — PAYMENTS
-- Payment records with idempotency keys (ADR-006).
-- Amount stored in tambala. One-to-one with shipment per active payment.
-- Multiple payment attempts are allowed (e.g. retry after failure)
-- but only one can be in 'processing' or 'paid' state per shipment.
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE payments (
  id                       UUID              NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  shipment_id              UUID              NOT NULL
    REFERENCES shipments(id) ON DELETE RESTRICT,
  user_id                  UUID              NOT NULL
    REFERENCES user_profiles(id) ON DELETE RESTRICT,

  -- ─── Monetary amount ────────────────────────────────────────────
  -- Must match shipment.final_price_mwk (or quoted_price_mwk if not adjusted).
  -- Validated in the backend before INSERT.
  amount_mwk               INTEGER           NOT NULL
    CONSTRAINT payments_amount_positive CHECK (amount_mwk > 0),

  -- ─── Payment method and status ──────────────────────────────────
  method                   payment_method    NOT NULL,
  status                   payment_status    NOT NULL DEFAULT 'pending',

  -- ─── Paychangu integration ──────────────────────────────────────
  -- provider_reference: Paychangu tx_ref (our reference we generate)
  -- provider_transaction_id: Paychangu's internal ID (from callback)
  provider_reference       TEXT              UNIQUE,
  provider_transaction_id  TEXT,

  -- ─── Idempotency (ADR-006) ──────────────────────────────────────
  -- UUID generated by mobile client before POST /api/payments/initiate.
  -- If same key is used again, return existing record without reprocessing.
  idempotency_key          TEXT              NOT NULL UNIQUE,

  -- ─── Mobile money specific ──────────────────────────────────────
  -- Required for airtel_money and tnm_mpamba methods.
  phone_number             TEXT
    CONSTRAINT payments_phone_format
      CHECK (phone_number IS NULL OR phone_number ~ '^\+?[0-9]{9,15}$'),

  -- ─── Webhook data ───────────────────────────────────────────────
  callback_received_at     TIMESTAMPTZ,
  callback_payload         JSONB,            -- Raw webhook body for forensics

  -- ─── Failure handling ───────────────────────────────────────────
  failure_reason           TEXT
    CONSTRAINT payments_failure_reason_length
      CHECK (failure_reason IS NULL OR char_length(failure_reason) <= 500),

  -- ─── Expiry ─────────────────────────────────────────────────────
  -- 30 minutes from creation. Cron job marks expired payments.
  expires_at               TIMESTAMPTZ       NOT NULL,

  -- ─── Timestamps ─────────────────────────────────────────────────
  created_at               TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_payments_shipment_id       ON payments (shipment_id);
CREATE INDEX idx_payments_user_id           ON payments (user_id);
CREATE INDEX idx_payments_status            ON payments (status);
CREATE INDEX idx_payments_provider_ref      ON payments (provider_reference) WHERE provider_reference IS NOT NULL;
CREATE INDEX idx_payments_expires_at        ON payments (expires_at) WHERE status IN ('pending', 'processing');
-- JSONB index for webhook payload lookup
CREATE INDEX idx_payments_callback_payload  ON payments USING gin (callback_payload) WHERE callback_payload IS NOT NULL;

-- Business rule: at most one active payment per shipment
-- "Active" = pending or processing. Paid payments are the permanent record.
CREATE UNIQUE INDEX idx_payments_one_active_per_shipment
  ON payments (shipment_id)
  WHERE status IN ('pending', 'processing');

-- Trigger: auto-update updated_at
CREATE TRIGGER set_payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- Comments
COMMENT ON TABLE  payments                       IS 'Payment records. One active payment per shipment at a time. Tambala (MWK × 100).';
COMMENT ON COLUMN payments.idempotency_key       IS 'UUID from mobile client. Prevents duplicate payments on network retry (ADR-006).';
COMMENT ON COLUMN payments.provider_reference    IS 'Our tx_ref sent to Paychangu. Unique. Used to correlate webhook callbacks.';
COMMENT ON COLUMN payments.callback_payload      IS 'Raw Paychangu webhook body. Stored for forensics and reconciliation.';
COMMENT ON COLUMN payments.expires_at            IS '30 min from creation. Backend worker marks stale payments as expired.';

-- ─── Row-Level Security ────────────────────────────────────────────
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Customers: read their own payments
CREATE POLICY "payments: owner can read"
  ON payments FOR SELECT
  USING (auth.uid() = user_id);

-- Customers: cannot INSERT directly — backend service role only
-- (Idempotency key validation happens in application code)

-- Admins: read all payments
CREATE POLICY "payments: admin can read all"
  ON payments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles up
      WHERE up.id = auth.uid() AND up.role IN ('admin', 'super_admin')
    )
  );
